docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - "PSR-11 Support": psr-11.md
        - Configuration: config.md
        - "Injector": injector.md
        - "Code Generator": codegen.md
        - "v2 Documentation":
            - "Dependency Definitions": v2/definitions.md
            - "Instance Manager": v2/instance-manager.md
            - Configuration: v2/config.md
            - "Debugging And Complex Use Cases": v2/debugging-and-complex-use-cases.md
    - Cookbook:
        - "Usage with PSR-11 Containers": cookbook/use-with-psr-containers.md
        - "Usage with zend-servicemanager": cookbook/use-with-servicemanager.md
        - "Using AoT with Expressive and zend-servicemanager": cookbook/aot-guide.md
    - "Migration Guide": migration.md
site_name: zend-di
site_description: "Automated dependency injection and instance manager."
repo_url: 'https://github.com/zendframework/zend-di'
